keboola/job-queue-internal-api-php-client

- .dockerignore
- .gitignore
- Dockerfile
- LICENSE.md
- README.md
- azure-pipelines.yml
- composer.json
- docker-compose.yml
- docker/php/php.ini
- phpcs.xml
- phpstan.neon
- phpunit.xml.dist
- src/Client.php
- src/ClientException.php
- tests/ClientTest.php
> initial import

- azure-pipelines.yml
- src/JobFactory.php
- src/JobFactory/Job.php
- tests/JobFactory/JobTest.php
- tests/JobFactoryTest.php
part of https://keboola.atlassian.net/browse/PS-27
> feat: legacy components handling

- src/JobFactory/FullJobDefinition.php
- src/JobFactory/Job.php
- tests/JobFactory/FullJobDefinitionTest.php
- tests/JobFactory/JobTest.php
relax job contraints so that orchestration jobs can be listed https://keboola.slack.com/archives/C13CP6YMV/p1575885830002100?thread_ts=1575639391.000600&cid=C13CP6YMV
> fix: support orchestration jobs

- src/JobFactory.php
- src/JobFactory/NewJobDefinition.php
- tests/ClientFunctionalTest.php
- tests/JobFactory/NewJobDefinitionTest.php
- tests/JobFactoryTest.php
https://keboola.slack.com/archives/C13CP6YMV/p1576077973003900
> Odin ps 30 new job

- tests/ClientTest.php
tak rekl bych, ze dobry :)
depends on https://github.com/keboola/job-queue-internal-api-php-client/pull/22
>  tests: make them faster!

- src/JobFactory/NewJobDefinition.php
- tests/JobFactory/NewJobDefinitionTest.php
refactor: make mode default to run, because that is 99% of jobs
depends on #23
> Make run default

- azure-pipelines.yml
- docker-compose.yml
- src/JobFactory.php
- src/JobFactory/Job.php
- src/JobFactory/NewJobDefinition.php
- tests/ClientFunctionalTest.php
- tests/ClientTest.php
- tests/JobFactory/JobTest.php
- tests/JobFactory/NewJobDefinitionTest.php
Depends on https://github.com/keboola/job-queue-internal-api/pull/47. Tests are failing.
> PS-135: fix (JobFactory): init new job with empty result

- src/JobFactory.php
- tests/JobFactoryTest.php
je to uz tady https://github.com/keboola/job-queue-api/blob/master/src/App.php#L29, ale potrebuju to i v demonovi, navic me prijde, ze se to hodi k tem ostatnim metodam
pri updatu to pak z api vyhodim
> add list of killable statuses

- .gitignore
- src/JobFactory.php
- tests/JobFactoryTest.php
> fix: don't leak token in error message

- src/JobFactory.php
- tests/ClientFunctionalTest.php
https://keboola.slack.com/archives/C02CGK5CL/p1579015126070000
> add component node for backward compatibility

- README.md
- azure-pipelines.yml
- docker-compose.yml
- docker/phpunit.sh
https://keboola.atlassian.net/browse/PS-980
prepojeny na image nove fronty - ten se generuje tu https://github.com/keboola/job-queue-internal-api/pull/6
testy failuji, protoze tam jsou zmeny API, tohle je jen zacatek
> use new internal api image for tests

- Dockerfile
- docker/php/php.ini
- src/Client.php
tuhle vyjimku nikdy zachytavat nebudem :)
> remove annoying warning

- phpstan.neon
- src/Client.php
- src/Exception/ClientException.php
- src/Exception/StateTargetEqualsCurrentException.php
- src/JobFactory.php
- src/JobFactory/StorageClientFactory.php
- tests/ClientFunctionalTest.php
- tests/ClientTest.php
- tests/JobFactory/StorageClientFactoryTest.php
- tests/JobFactoryTest.php
refactor: move exception to its namespace
https://keboola.atlassian.net/browse/PS-1576
> feat: handle invalid state transition

- src/Client.php
- tests/ClientTest.php
https://keboola.atlassian.net/browse/PS-1672
> chunk getJobwithIds

- src/Client.php
- src/JobListOptions.php
- tests/ClientFunctionalTest.php
- tests/ClientTest.php
https://keboola.atlassian.net/browse/PS-1690
> feat: page list jobs

- README.md
- src/Client.php
- src/JobFactory.php
- src/JobFactory/Job.php
- src/JobFactory/JobInterface.php
add job interface so that job can be decorated easily 
related to https://github.com/keboola/job-queue-daemon/pull/109
> Odin ps 1715

- src/Client.php
- src/JobFactory/JobResult.php
- tests/ClientFunctionalTest.php
- tests/ClientTest.php
- tests/JobFactory/JobResultTest.php
Introduces a more strict structure on the job result
https://keboola.atlassian.net/browse/PS-1673
> JobResult class

- tests/ClientFunctionalTest.php
Ono sa totiz tie zatvorky "[]" vzdy urlencodnu, takze potom v tej uri nie je mozne rozlisit, ktore zatvorky oznacuju pole a ktore su sucastou hodnoty (IMHO).
https://github.com/guzzle/psr7/blob/7858757f390bbe4b3d81762a97d6e6e786bb70ad/src/Uri.php#L662
> PS-1483: component id can't contain [] characters

- src/Client.php
- src/JobPatchData.php
- tests/ClientFunctionalTest.php
- tests/ClientTest.php
- tests/JobPatchDataTest.php
Tie gettery su v tej JobPatchData triede asi zbytocne, som si potom uvedomil.
> feat: patchJob method

- src/Client.php
- tests/ClientTest.php
https://keboola.atlassian.net/browse/PS-1864
> PS-1864 Do not accept empty jobId in Client->getJob/updateJob

- src/Client.php
- tests/ClientTest.php
https://keboola.atlassian.net/browse/PS-1933
> fix: pagination with list IDs

- .dockerignore
- composer.json
- tests/ClientFunctionalTest.php
- tests/ClientTest.php
- tests/JobFactory/FullJobDefinitionTest.php
- tests/JobFactory/NewJobDefinitionTest.php
- tests/JobFactoryTest.php
part of https://keboola.atlassian.net/browse/PS-2033
> PS-2033 fix: relax dependency requirements

- phpstan.neon
- src/JobFactory.php
- src/JobFactory/FullJobDefinition.php
- src/JobFactory/Job.php
- src/JobFactory/JobInterface.php
- src/JobFactory/NewJobDefinition.php
- tests/ClientFunctionalTest.php
- tests/ClientTest.php
- tests/JobFactory/FullJobDefinitionTest.php
- tests/JobFactory/JobTest.php
- tests/JobFactoryTest.php
https://keboola.atlassian.net/browse/PS-1845
feat: allow branchId in job
fix: make runId required as it already is https://keboola.slack.com/archives/C13CP6YMV/p1618310117060700
> dpm support in internal API client

- src/JobListOptions.php
- tests/ClientFunctionalTest.php
- tests/JobListOptionsTest.php
https://keboola.atlassian.net/browse/PS-1918
> PS-1918: feat: list jobs by configRowIds

- src/JobFactory/FullJobDefinition.php
- src/JobFactory/Job.php
- src/JobFactory/JobInterface.php
- src/JobFactory/NewJobDefinition.php
- tests/JobFactory/JobTest.php
https://keboola.atlassian.net/browse/PS-2109
> variables support

- docker-compose.yml
- src/JobFactory.php
- src/JobFactory/Job.php
- tests/ClientFunctionalTest.php
- tests/ClientTest.php
- tests/JobFactory/JobTest.php
- tests/JobFactoryTest.php
fix: undefined variable values id
fix: initialize variables on a new job correctly
fix: update for latest internal api
> několik bugísků

- src/Client.php
- src/JobFactory.php
- src/JobFactory/Backend.php
- src/JobFactory/FullJobDefinition.php
- src/JobFactory/Job.php
- src/JobFactory/JobInterface.php
- src/JobFactory/NewJobDefinition.php
- tests/JobFactory/BackendTest.php
- tests/JobFactory/FullJobDefinitionTest.php
- tests/JobFactory/JobTest.php
- tests/JobFactory/NewJobDefinitionTest.php
- tests/JobFactoryTest.php
https://keboola.atlassian.net/browse/PS-2246
Depends on https://github.com/keboola/job-queue-internal-api/pull/64
> PS-2246 Configurable workspace backend

- tests/ClientFunctionalTest.php
https://keboola.atlassian.net/browse/PS-2246
> PS-2246 Fix tests after internal API update

- src/JobFactory/Backend.php
- tests/JobFactory/BackendTest.php
https://keboola.atlassian.net/browse/PS-2257
> PS-2257 Allow export Backend configuration as array

- composer.json
- phpstan.neon
- src/JobFactory/Backend.php
- src/JobFactory/Job.php
- src/JobFactory/JobInterface.php
- src/JobFactory/JobRuntimeResolver.php
- src/JobFactory/OverridesConfigurationDefinition.php
- src/JobFactory/VariableValues.php
- tests/JobFactory/BackendTest.php
- tests/JobFactory/JobRuntimeResolverTest.php
- tests/JobFactory/NewJobDefinitionTest.php
- tests/JobFactory/OverridesConfigurationDefinitionTest.php
- tests/JobFactory/VariableValuesTest.php
https://keboola.atlassian.net/browse/PS-2286
> feat: resolve overriding values

- src/JobFactory/JobRuntimeResolver.php
- src/JobFactory/OverridesConfigurationDefinition.php
- tests/JobFactory/JobRuntimeResolverTest.php
fix: handle improperly deployed components gracefully
fix: read tag from image_tag too https://keboola.slack.com/archives/CQB468K63/p1624543038092300
> resolver fixes

- docker-compose.yml
vrátil jsem to, comitnul jsem to, akorát jsem zmáčkl nejdřív merge a pak push
> fix: use latest image

- src/Client.php
- src/JobFactory/FullJobDefinition.php
- src/JobFactory/Job.php
- src/JobFactory/JobInterface.php
- src/JobFactory/JobResult.php
- src/JobFactory/OverridesConfigurationDefinition.php
- src/JobPatchData.php
- tests/ClientFunctionalTest.php
- tests/ClientTest.php
- tests/JobFactoryTest.php
- tests/JobListOptionsTest.php
refactor: make postJobResult and patchJob return Job instead of array
feat: add getStartTime and getEndTime methods
> Notifications support
